/// Pure-Dart port of HisabCore. Mirrors the Swift package module-for-module;
/// the Swift sources are the executable specification.
library;

export 'src/analytics.dart';
export 'src/capture/alert_capture.dart';
export 'src/capture/alert_parser.dart';
export 'src/capture/category_ranker.dart';
export 'src/capture/memo_merger.dart';
export 'src/capture/notification_policy.dart';
export 'src/capture/pending_memo.dart';
export 'src/capture/rule_impact.dart';
export 'src/categories.dart';
export 'src/extractor/alert_extractor.dart';
export 'src/extractor/extracted_alert.dart';
export 'src/extractor/extractor_decode.dart';
export 'src/extractor/extractor_normalize.dart';
export 'src/extractor/extractor_tokenizer.dart';
export 'src/generic_bank/chain_interpreter.dart';
export 'src/generic_bank/column_inference.dart';
export 'src/generic_bank/format_fingerprint.dart';
export 'src/generic_bank/format_spec.dart';
export 'src/generic_bank/import_resolver.dart';
export 'src/generic_bank/minimal_xls.dart';
export 'src/generic_bank/normalized_table.dart';
export 'src/generic_bank/spec_executor.dart';
export 'src/generic_bank/statement_date.dart';
export 'src/generic_bank/synthetic_ref.dart';
export 'src/generic_bank/xlsx_reader.dart';
export 'src/parsers/parsers.dart';
export 'src/content_hash.dart';
export 'src/coverage.dart';
export 'src/dedup.dart';
export 'src/domain.dart';
export 'src/insights/anomaly_detector.dart';
export 'src/insights/complete_months.dart';
export 'src/insights/insight.dart';
export 'src/insights/insights_config.dart';
export 'src/insights/insights_engine.dart';
export 'src/insights/recurrence_detector.dart';
export 'src/insights/trend_detector.dart';
export 'src/money.dart';
export 'src/reconciliation.dart';
export 'src/self_transfers.dart';
export 'src/suggestion_engine.dart';
export 'src/year_month.dart';
