// Cross-language ground-truth validation: every real statement in samples/
// must parse to the exact hash set the Swift parsers produced
// (samples_groundtruth.json, generated by SamplesGroundTruthDump.swift).
// Local-only: skipped when samples/ or the ground truth is absent.
@Tags(['samples'])
library;

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:hisab_core/hisab_core.dart';
import 'package:hisab_pdf/hisab_pdf.dart';

const samplesDir = '/Users/vedant/personal/hisab/samples';
const groundTruthPath = '../hisab_core/test/samples_groundtruth.json';
const passwords = {'Acct Statement_3293_23062026_13.38.47.pdf': '135244908'};

/// Formats the Swift core parses but the Dart port deliberately does not
/// (with the reason documented where the decision was made).
const knownUnsupported = {
  // Syncfusion drops glyphs in this statement's embedded font — rail
  // references would silently corrupt, so Android refuses the PDF rendition
  // and users import the XLSX rendition of the same statement instead.
  'idfc/IDFCFIRSTBankstatement_10061308816.pdf',
};

void main() {
  final available = Directory(samplesDir).existsSync() &&
      File(groundTruthPath).existsSync();

  test('every sample matches the Swift hash set exactly', () {
    if (!available) {
      markTestSkipped('samples or ground truth not present');
      return;
    }
    final groundTruth = jsonDecode(File(groundTruthPath).readAsStringSync())
        as Map<String, dynamic>;
    final registry = fullRegistry();

    final failures = <String>[];
    groundTruth.forEach((relPath, expectedRaw) {
      final expected = expectedRaw as Map<String, dynamic>;
      if (expected.containsKey('error')) return;
      final file = File('$samplesDir/$relPath');
      if (!file.existsSync()) {
        failures.add('$relPath: sample missing');
        return;
      }
      final data = file.readAsBytesSync();
      final filename = relPath.split('/').last;
      final parser = registry.detect(data, filename);
      if (parser == null) {
        if (knownUnsupported.contains(relPath)) return;
        failures.add('$relPath: no Dart parser detected it');
        return;
      }
      try {
        final doc = parser.parse(data, password: passwords[filename]);
        final hashes =
            doc.transactions.map((t) => t.contentHash(doc.source)).toList()
              ..sort();
        final expectedHashes =
            (expected['hashes'] as List).cast<String>()..sort();
        if (doc.source.rawValue != expected['source']) {
          failures.add(
              '$relPath: source ${doc.source} != ${expected['source']}');
        }
        if (doc.transactions.length != expected['count']) {
          failures.add(
              '$relPath: count ${doc.transactions.length} != ${expected['count']}');
        } else if (!_equal(hashes, expectedHashes)) {
          var diff = 0;
          final expectedSet = expectedHashes.toSet();
          for (final h in hashes) {
            if (!expectedSet.contains(h)) diff++;
          }
          failures.add('$relPath: $diff/${hashes.length} hashes differ');
        }
      } catch (e) {
        failures.add('$relPath: threw $e');
      }
    });
    expect(failures, isEmpty, reason: failures.join('\n'));
  }, timeout: const Timeout(Duration(minutes: 10)));

  test('IDFC PDF glyph-fidelity probe (documents why it is unsupported)', () {
    if (!available) {
      markTestSkipped('samples not present');
      return;
    }
    final data =
        File('$samplesDir/idfc/IDFCFIRSTBankstatement_10061308816.pdf')
            .readAsBytesSync();
    final text = PdfText.pageTexts(data, null)!.join('\n');
    // The XLSX rendition of the same statement carries "UPI/DR/" rails; if
    // Syncfusion rendered glyphs faithfully these would appear in the PDF
    // text too. When this expectation ever FAILS (i.e. the text becomes
    // faithful after a Syncfusion upgrade), revisit enabling the PDF parser.
    expect(text.contains('UPI/DR/'), isFalse,
        reason: 'Syncfusion now renders IDFC glyphs faithfully — '
            'consider enabling an IDFC PDF parser');
  });
}

bool _equal(List<String> a, List<String> b) {
  if (a.length != b.length) return false;
  for (var i = 0; i < a.length; i++) {
    if (a[i] != b[i]) return false;
  }
  return true;
}
