/// The extractor's tokenizer: BERT normalizer -> BERT pre-tokenizer -> Digits
/// -> WordPiece (uncased), without any Unicode database. Port of
/// ml/src/hisab_ml/wordpiece.py `encode` and features.py `prepare`; the
/// Unicode facts come from chartable.json, generated by the Python reference.
///
/// Every index is a Unicode SCALAR index (a Python code point index), never a
/// UTF-16 one.
library;

import 'dart:convert';

/// Token ids and, per token, the `(start, end)` scalar range of the original
/// text it came from; `(0, 0)` for `[CLS]` and `[SEP]`.
class ExtractorEncoding {
  final List<int> ids;
  final List<(int, int)> offsets;
  const ExtractorEncoding(this.ids, this.offsets);
}

class ExtractorTokenizer {
  static const _maxWordChars = 100;

  /// BERT's CJK blocks: each ideograph becomes its own word.
  static const _cjk = [
    (0x4E00, 0x9FFF), (0x3400, 0x4DBF), (0x20000, 0x2A6DF), //
    (0x2A700, 0x2B73F), (0x2B740, 0x2B81F), (0x2B820, 0x2CEAF),
    (0xF900, 0xFAFF), (0x2F800, 0x2FA1F),
  ];

  final Map<String, int> _vocab;
  final int _cls, _sep, _unk;

  /// Ranges flattened as `[lo0, hi0, lo1, hi1, ...]`, sorted.
  final List<int> _removed, _punct, _numeric;

  /// Scalar -> its normalized scalars (NFD, marks dropped, lowercased).
  final Map<int, List<int>> _map;

  /// Same-length character map applied before tokenizing (₹ -> $, • -> *).
  final Map<int, int> _charMap;

  final int maxLen;

  ExtractorTokenizer._(this._vocab, this._removed, this._punct, this._numeric,
      this._map, this._charMap, this.maxLen)
      : _cls = _vocab['[CLS]']!,
        _sep = _vocab['[SEP]']!,
        _unk = _vocab['[UNK]']!;

  /// From the asset strings: vocab.txt, chartable.json and extractor.json.
  factory ExtractorTokenizer.fromStrings({
    required String vocab,
    required String chartable,
    required String config,
  }) {
    // One token per line, id = line number (blank lines skipped, not renumbered).
    final ids = <String, int>{};
    final lines = vocab.split('\n');
    for (var i = 0; i < lines.length; i++) {
      if (lines[i].isNotEmpty) ids[lines[i]] = i;
    }
    final table = jsonDecode(chartable) as Map<String, dynamic>;
    List<int> ranges(String key) => [
          for (final r in table[key] as List)
            for (final v in r as List) v as int
        ];
    final map = {
      for (final e in (table['map'] as Map<String, dynamic>).entries)
        int.parse(e.key): (e.value as String).runes.toList()
    };
    final cfg = jsonDecode(config) as Map<String, dynamic>;
    final charMap = {
      for (final e in (cfg['char_map'] as Map<String, dynamic>).entries)
        e.key.runes.single: (e.value as String).runes.single
    };
    return ExtractorTokenizer._(ids, ranges('removed'), ranges('punct'),
        ranges('numeric'), map, charMap, cfg['max_len'] as int);
  }

  /// features.prepare: the same-length character map.
  String prepare(String text) =>
      String.fromCharCodes(text.runes.map((c) => _charMap[c] ?? c));

  /// wordpiece.encode on already-[prepare]d text.
  ExtractorEncoding encode(String text) {
    final norm = _normalize(text);
    final ids = [_cls];
    final offsets = [(0, 0)];
    for (final (a, b) in _words(norm.chars)) {
      for (final (id, s, e) in _wordpiece(norm.chars, a, b)) {
        if (ids.length == maxLen - 1) break;
        ids.add(id);
        offsets.add((norm.source[a + s], norm.source[a + e - 1] + 1));
      }
    }
    ids.add(_sep);
    offsets.add((0, 0));
    return ExtractorEncoding(ids, offsets);
  }

  /// Normalized scalars, each with the index of the original scalar it came
  /// from.
  ({List<int> chars, List<int> source}) _normalize(String text) {
    final chars = <int>[];
    final source = <int>[];
    var i = 0;
    for (final cp in text.runes) {
      if (_isWhiteSpace(cp)) {
        chars.add(0x20);
        source.add(i);
      } else if (_in(_removed, cp)) {
        // dropped
      } else if (_cjk.any((r) => r.$1 <= cp && cp <= r.$2)) {
        chars.addAll([0x20, cp, 0x20]);
        source.addAll([i, i, i]);
      } else {
        for (final c in _map[cp] ?? [cp]) {
          chars.add(c);
          source.add(i);
        }
      }
      i++;
    }
    return (chars: chars, source: source);
  }

  /// Words as `[start, end)` ranges of [chars]: split on spaces (dropped),
  /// isolate each punctuation character, then split digit runs from the rest.
  List<(int, int)> _words(List<int> chars) {
    final words = <(int, int)>[];
    var start = 0; // current word is [start, i)
    for (var i = 0; i < chars.length; i++) {
      final cp = chars[i];
      if (cp == 0x20) {
        if (start < i) words.add((start, i));
        start = i + 1;
      } else if (_isPunct(cp)) {
        if (start < i) words.add((start, i));
        words.add((i, i + 1));
        start = i + 1;
      } else if (start < i &&
          _in(_numeric, chars[i - 1]) != _in(_numeric, cp)) {
        words.add((start, i));
        start = i;
      }
    }
    if (start < chars.length) words.add((start, chars.length));
    return words;
  }

  /// `(id, start, end)` pieces relative to the word `chars[a, b)`, or one
  /// `[UNK]` for the whole word.
  List<(int, int, int)> _wordpiece(List<int> chars, int a, int b) {
    final n = b - a;
    if (n > _maxWordChars) return [(_unk, 0, n)];
    final pieces = <(int, int, int)>[];
    var start = 0;
    while (start < n) {
      var end = n;
      int? hit;
      while (start < end) {
        final sub = String.fromCharCodes(chars, a + start, a + end);
        hit = _vocab[start == 0 ? sub : '##$sub'];
        if (hit != null) break;
        end--;
      }
      if (hit == null) return [(_unk, 0, n)];
      pieces.add((hit, start, end));
      start = end;
    }
    return pieces;
  }

  static bool _isWhiteSpace(int cp) =>
      (cp >= 0x09 && cp <= 0x0D) ||
      cp == 0x20 ||
      cp == 0x85 ||
      cp == 0xA0 ||
      cp == 0x1680 ||
      (cp >= 0x2000 && cp <= 0x200A) ||
      cp == 0x2028 ||
      cp == 0x2029 ||
      cp == 0x202F ||
      cp == 0x205F ||
      cp == 0x3000;

  bool _isPunct(int cp) =>
      (cp >= 0x21 && cp <= 0x2F) ||
      (cp >= 0x3A && cp <= 0x40) ||
      (cp >= 0x5B && cp <= 0x60) ||
      (cp >= 0x7B && cp <= 0x7E) ||
      _in(_punct, cp);

  static bool _in(List<int> ranges, int cp) {
    var lo = 0, hi = ranges.length ~/ 2 - 1;
    while (lo <= hi) {
      final mid = (lo + hi) ~/ 2;
      if (cp < ranges[2 * mid]) {
        hi = mid - 1;
      } else if (cp > ranges[2 * mid + 1]) {
        lo = mid + 1;
      } else {
        return true;
      }
    }
    return false;
  }
}
